version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5004:5000
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@api-db:5432/api_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@api-db:5432/api_test
    depends_on:
      - api-db

  api-db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    stdin_open: true
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - './services/client:/usr/src/app'
      # Using anonymous volumes so that node_modules isn't overwritten when the container mounts
      # See https://web.archive.org/web/20200612000749if_/https://success.docker.com/article/different-types-of-volumes
      - '/usr/src/app/node_modules'
    ports:
      - 3007:5173
    environment:
      - NODE_ENV=development
      - VITE_API_SERVICE_URL=${VITE_API_SERVICE_URL}
    depends_on:
      - api
