# pull official base image
FROM node:20.16.0

# set working directory
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH
ENV NODE_ENV development

# install and cache app dependencies
COPY package.json .
COPY package-lock.json .
RUN npm ci
RUN npm install prettier@3.3.3 eslint@8.57.0 -g --silent

# add app
COPY . .

# start app
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
