name: Release

on: workflow_dispatch

jobs:
  test-python:
    name: Test Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.0"
      - name: Install Dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Lint
        run: |
          python -m flake8 src
          python -m isort src --check-only
      # TODO: fix this. It is failing because you don't have a database
      # - name: Test
      #   run: |
      #     python -m pytest "src/tests" -p no:warnings
      - name: Format
        run: |
          python -m black src --check
  test-client:
    name: Test Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/client
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"
      - name: Install Dependencies
        run: |
          npm ci
      - name: Lint
        run: |
          npm run prettier:check
      - name: Test
        run: |
          npm run test
      - name: Format
        run: |
          npm run prettier:check
